### ISSUE TITLE
Error when testing

### ISSUE THREAD

**Issue by Cecca** [Zjut-MultimediaPlus/DADH#4]
I am getting an error when testing the `mir` dataset.
These are the contents of my `data` directory, with data downloaded as per the README

```
> ls data
FLICKR-25K.mat  README.md  imagenet-vgg-f.mat
```

After training (successfully) with 

```
python3 main.py train --flag 'mir' --bit 16
```

I tried testing with

```
python3 main.py test --flag 'mir' --bit 16
```

but got the following error:

```
Configuration:
        load_model_path: None
        pretrain_model_path: ./data/imagenet-vgg-f.mat
        vis_env: main
        vis_port: 8097
        flag: mir
        batch_size: 128
        image_dim: 4096
        hidden_dim: 8192
        modals: 2
        valid: True
        valid_freq: 1
        max_epoch: 300
        bit: 16
        lr: 5e-05
        device: cuda:0
        alpha: 10
        gamma: 1
        beta: 1
        mu: 1e-05
        lamb: 1
        margin: 0.4
        dropout: False
Traceback (most recent call last):
  File "main.py", line 335, in <module>
    fire.Fire()
  File "/home/clusterusers/mceccarello/.local/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/clusterusers/mceccarello/.local/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/clusterusers/mceccarello/.local/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "main.py", line 260, in test
    generator = GEN(opt.image_dim,
TypeError: __init__() missing 1 required positional argument: 'class_dim'
```

Is there any way I can fix it?

**Comment by flyfish7** [comment]
I've fixed the bug, you should have no problems running test now.

**Comment by Cecca** [comment]
Now it works, thank you!
